M48
; DRILL file {KiCad 7.0.10} date Sun Feb  4 18:23:57 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-04T18:23:57-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0492
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.363Y-4.013
T2
X4.75Y-2.75
X4.75Y-4.35
X5.35Y-2.75
X5.35Y-4.35
M30
